language: java
install: ant
script: ant build
deploy:
  provider: releases
  api_key: $TOKEN
  file: dist/filecoverage-extension.lex
  skip_cleanup: true
  on:
    repo: cybersonic/lucee-filecoverage-extension
    branch: develop
    tags: true